steps:
# Build Backend
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/intuitionsearch-1719465776066/travel-planner-backend:latest'
  - './backend'
  - '-f'
  - './backend/Dockerfile'
  
# Build Frontend
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/intuitionsearch-1719465776066/travel-planner-frontend:latest'
  - './frontend'
  - '-f'
  - './frontend/Dockerfile'
  - '--build-arg'
  - 'VITE_API_BASE_URL=https://travel-planner-backend-dot-intuitionsearch-1719465776066.uc.r.appspot.com/api/v1'
  - '--build-arg'
  - 'VITE_FIREBASE_PROJECT_ID=intuitionsearch-1719465776066'

# Push Backend Image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/intuitionsearch-1719465776066/travel-planner-backend:latest'

# Push Frontend Image  
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/intuitionsearch-1719465776066/travel-planner-frontend:latest'

# Deploy Backend to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'travel-planner-backend'
  - '--image=gcr.io/intuitionsearch-1719465776066/travel-planner-backend:latest'
  - '--region=us-central1'
  - '--platform=managed'
  - '--allow-unauthenticated'
  - '--port=8080'
  - '--memory=2Gi'
  - '--cpu=2'
  - '--min-instances=0'
  - '--max-instances=10'
  - '--set-env-vars=NODE_ENV=production,PORT=8080,GOOGLE_CLOUD_PROJECT_ID=intuitionsearch-1719465776066'

# Deploy Frontend to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'travel-planner-frontend'
  - '--image=gcr.io/intuitionsearch-1719465776066/travel-planner-frontend:latest'
  - '--region=us-central1'
  - '--platform=managed'
  - '--allow-unauthenticated'
  - '--port=80'
  - '--memory=512Mi'
  - '--cpu=1'
  - '--min-instances=0'
  - '--max-instances=5'

images:
- 'gcr.io/intuitionsearch-1719465776066/travel-planner-backend:latest'
- 'gcr.io/intuitionsearch-1719465776066/travel-planner-frontend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'